### ISSUE TITLE
Generic TODO list

### ISSUE THREAD

**Issue by JuliaPoo** [Fidget-Spinner/cpython#51]
- [ ] `try_hoist_guard` to support constant inputs, codegen to be modified accordingly
- [ ] Copy over immutables' type and other type information into the new store when creating a new impure region
- [ ] For a sane debugging experience, add a `print_sym` function
- [x] `_CHECK_CALL_BOUND_METHOD_EXACT_ARGS` can potentially be a guard
- [ ] Implement `_PyOpcode_isimmutable`
- [ ] Update stack space for frames that requires it
- [ ] Implement function inlining
- [ ] Implement the "locals at end of trace" to support CSE

**Comment by Fidget-Spinner** [comment]
Memory optimizations:
- [ ] Make an arena for all sym expressions.
- [ ] Make the hash function not allocate anything.

We should do this at the end, before proposing upstream to CPython. Since this will affect interpreter stall times.
